# Configuration for Auto Labeler during pull request
#
# See https://github.com/actions/labeler for file format

"c#":
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.cs'
      - 'net/**/*'

compiler:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**/*'
      - 'include/**/*'
      - 'CMakeLists.txt'

codegen:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/idl_gen_csharp_spanbufs.*'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'

CI:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'

scripts:
  - changed-files:
    - any-glob-to-any-file:
      - 'scripts/**/*'
